[Main Map] Add icons to map type dialog
google/ground-android pull request #1552
Opened 2023-02-11 08:23 UTC by shobhitagarwal1612

Fixes #1544 

Adds new icons and improve ux

<img src="https://user-images.githubusercontent.com/8918023/218248145-7378d89a-9095-41a1-a081-47f50a3b764e.png"  width="300" height="666">

@JSunde @gino-m  PTAL?

2023-02-11 13:00 UTC, shobhitagarwal1612 commented
/gcbrun

2023-02-13 14:41 UTC, JSunde approved these changes

2023-02-13 16:54 UTC, shobhitagarwal1612 commented
/gcbrun

2023-02-13 16:57 UTC, gino-m requested changes

2023-02-13 16:57 UTC, gino-m commented on ground/src/main/res/layout/map_type_dialog_item.xml
> +    tools:src="@drawable/ic_type_roadmap" />
Layout nit: Can we align the left and right sides of the images with the "Map type" header and close button?

2023-02-13 16:57 UTC, gino-m commented on ground/src/main/res/layout/map_type_dialog_item.xml
> +    android:layout_width="128dp"
Is it easy to also give the images rounded corners?

2023-02-13 18:45 UTC, shobhitagarwal1612 commented
/gcbrun

2023-02-15 19:05 UTC, shobhitagarwal1612 commented
/gcbrun

2023-02-16 17:53 UTC, shobhitagarwal1612 commented
/gcbrun

2023-02-16 17:53 UTC, shobhitagarwal1612 commented
@gino-m Gentle ping!

2023-02-22 00:27 UTC, gino-m commented on ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt
> +  val basemapType: LiveData<Int>
Nit: `baseMapType`

2023-02-22 16:19 UTC, gino-m commented
/gcbrun

2023-02-22 16:19 UTC, gino-m approved these changes
🗺️ 👍

2023-02-22 17:33 UTC, merged