Animate progress bar changes in data collection flow
google/ground-android pull request #1796
Opened 2023-08-14 19:02 UTC by JSunde

Fixes #1794

https://github.com/google/ground-android/assets/9056308/76454515-d849-49bc-a70d-ef17c391359f

2023-08-14 19:03 UTC, JSunde commented
/gcbrun

2023-08-15 11:05 UTC, gino-m requested changes
One nit, otherwise LG

2023-08-15 11:05 UTC, gino-m commented on ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
> +      val updatedProgress = it.animatedValue as Int
Can this variable be inlined?

2023-08-15 16:34 UTC, JSunde commented on ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionFragment.kt
> +      val updatedProgress = it.animatedValue as Int
Done!

2023-08-15 16:42 UTC, gino-m approved these changes

2023-08-15 17:08 UTC, merged