Allow user to signout if surveys are not avaiable
google/ground-android pull request #2002
Opened 2023-10-20 14:14 UTC by shobhitagarwal1612

Fixes #1879

@gino-m  PTAL?

2023-10-20 15:03 UTC, gino-m requested changes

2023-10-20 15:06 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
> +  var surveyAvailable: LiveData<Boolean?>
Done

2023-10-20 15:06 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
> +  var surveyAvailable: LiveData<Boolean?>
Thanks! Done

2023-10-20 15:07 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
> +    surveyAvailable = surveySummaries.map { it.isNotEmpty() }.onStart { emit(true) }.asLiveData()
We don't have a progress spinner when the surveys are refreshing. The initial true value prevents displaying the empty screen when the screen is loading.

2023-10-21 06:52 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveySelectorViewModel.kt
> +    surveyAvailable = surveySummaries.map { it.isNotEmpty() }.onStart { emit(true) }.asLiveData()
This is now done. Thanks for the suggestions!

2023-10-23 13:46 UTC, gino-m approved these changes
LGTM!

2023-10-23 13:46 UTC, merged