Adding sign out warning dialog to the home screen
google/ground-android pull request #2209
Opened 2024-01-26 15:26 UTC by justinkimtang

rebase

Fixes #1683

Adds a sign out confirmation screen to Ground, warning users that unsaved data will be lost on sign out. Currently this is only implemented for sign outs from the home screen fragment.

- [x] Adds sign out dialog, fragment and viewmodel
- [x] Replaces navigation call on home screen with launch of sign out
- [ ] Copy sign off
- [ ] Sign out from other screens

Sign out of ground from the hamburger menu and verify that the screen comes up.
Clicking cancel should exit the dialog.
Clicking sign out should sign the user out.

https://github.com/google/ground-android/assets/77077870/fc4ea211-5796-4802-92bb-79e12d20d683

@gino-m  PTAL?

2024-01-26 15:40 UTC, gino-m commented
I'm OOO till next week. @shobhitagarwal1612 could you PTAL?

2024-01-26 15:51 UTC, justinkimtang commented
@amegantz what do you think about the copy?

2024-01-27 02:29 UTC, shobhitagarwal1612 requested changes

2024-01-27 02:29 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/common/SignOutConfirmationDialogViewModel.kt
> + * Copyright 2023 Google LLC
Please fix the year from 2023 to 2024. Same comment for other files too.

2024-01-27 02:29 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/common/SignOutConfirmationFragment.kt
> +
Please add the missing license header.

2024-01-27 02:29 UTC, shobhitagarwal1612 commented on ground/src/main/res/layout/sign_out_confirmation_dialog.xml
> +  ~ Copyright 2023 Google LLC
Same as above

2024-01-31 16:42 UTC, shobhitagarwal1612 approved these changes

2024-01-31 16:51 UTC, merged

2024-02-06 01:26 UTC, amegantz commented
**Unsaved data**
If you sign out, your unsaved data will be discarded.
[Cancel] [Sign out]