Increase worker retry count (also refactor constants into Config.kt).
google/ground-android pull request #2368
Opened 2024-03-15 02:38 UTC by sufyanAbbasi

Addresses #154

Increases worker retry count to mitigate issues involving jobs that exceed the worker count.

- [x] Increases worker retry count to 25.

PTAL @gino-m @shobhitagarwal1612 !

2024-03-15 06:51 UTC, shobhitagarwal1612 approved these changes

2024-03-15 06:53 UTC, shobhitagarwal1612 commented
One test is failing `Worker retries if retryCount is less than 10 for any mutation`. Can you please check?

2024-03-15 06:54 UTC, shobhitagarwal1612 requested changes
Please update the failing unit test.

2024-03-15 23:53 UTC, sufyanAbbasi commented
Done!

2024-03-16 06:02 UTC, shobhitagarwal1612 approved these changes
🔁

2024-03-16 06:02 UTC, merged