Use jetpack compose for buttons in task fragments
google/ground-android pull request #2414
Opened 2024-03-29 08:00 UTC by shobhitagarwal1612

Fixes #1795

This PR replaces xml layouts for action buttons with jetpack compose.

[compose-task-button.webm](https://github.com/google/ground-android/assets/8918023/ac841e8a-f91c-4ab9-84cb-e62fbb9ed5c2)

@gino-m  PTAL?

2024-03-29 13:54 UTC, gino-m requested changes
Overall looks good! @sufyanAbbasi Do you think this is safe to merge, or do we want to implement e2e testing first?

2024-03-29 13:54 UTC, gino-m commented on ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
> +            // TODO: Previous button should always be positioned to the left of the screen. Rest
Please add tracking bug.

2024-03-29 19:26 UTC, shobhitagarwal1612 commented
The tests are passing locally. Not sure what the problem is with remote builds.

2024-03-29 19:40 UTC, gino-m commented
> The tests are passing locally. Not sure what the problem is with remote builds.

The "Update build status" step failed, not the actual tests. Flake?

2024-03-29 20:27 UTC, shobhitagarwal1612 commented
We upload the results in this step and then fail the build. So this is WAI

2024-03-29 20:29 UTC, gino-m commented
> We upload the results in this step and then fail the build. So this is WAI

I see. So the actual error is in the unit tests:

```
com.google.android.ground.ui.signin.SignInFragmentTest > Back press should finish activity FAILED
    kotlinx.coroutines.test.UncaughtExceptionsBeforeTest at TestScope.kt:242
```

It seems the activity isn't closing on "Back" on GCB for some reason?

2024-03-29 20:30 UTC, shobhitagarwal1612 commented
I can see this test failing occasionally on local builds as well. Should we retry?

2024-03-30 05:24 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt
> +            // TODO: Previous button should always be positioned to the left of the screen. Rest
Done

2024-04-01 14:27 UTC, gino-m approved these changes
⏺️

2024-04-01 14:27 UTC, merged

2024-04-06 03:49 UTC, shobhitagarwal1612 commented
Even before this change, the buttons were generated dynamically without a resource ID. So we can use text or content description (for image buttons)