Display a snackbar when draft is restored
google/ground-android pull request #2666
Opened 2024-08-18 09:52 UTC by shobhitagarwal1612

Fixes #2303

[draft-restored-snackbar.webm](https://github.com/user-attachments/assets/83f04f6c-d141-4bfd-86ed-5f181c367c62)

@gino-m  PTAL?

2024-08-19 13:34 UTC, gino-m requested changes
LGTM! @amegantz for UXW approval

2024-08-19 13:34 UTC, gino-m commented on ground/src/main/res/values/strings.xml
> +  <string name="draft_restored">App was closed. Unsaved data restored.</string>
@amegantz For approval

2024-08-19 13:39 UTC, shobhitagarwal1612 commented
/gcbrun

2024-08-20 17:51 UTC, amegantz commented
"Unsynced data restored"?

2024-08-20 17:59 UTC, gino-m commented
> "Unsynced data restored"?

It's not that the data wasn't synced, it simply wasn't saved locally yet.

2024-08-21 18:09 UTC, amegantz commented
Sounds like "Unsaved data restored" should work?

2024-08-22 05:30 UTC, shobhitagarwal1612 commented
Updated the text string. @gino-m PTAL

2024-09-05 15:15 UTC, shobhitagarwal1612 commented
@gino-m Gentle ping!

2024-09-05 15:57 UTC, gino-m approved these changes

2024-09-05 16:25 UTC, merged