Index error handle
google/ground-android pull request #2778
Opened 2024-09-30 13:29 UTC by anandwana001

Fixes #2777 

@shobhitagarwal1612  PTAL?

2024-09-30 13:37 UTC, shobhitagarwal1612 requested changes
Please update the title of the PR to be something more specific

2024-09-30 13:37 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeDialogFragment.kt
> +      }
Can we fix the adapter itself to prevent invoking the callback if index is -1?

2024-10-01 02:44 UTC, anandwana001 commented on ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/MapTypeAdapter.kt
> +    if(position > -1 ) {
Done

2024-10-01 03:49 UTC, shobhitagarwal1612 commented
> Please update the title of the PR to be something more specific

Can you please resolve this as well?

2024-10-01 04:53 UTC, shobhitagarwal1612 approved these changes

2024-10-01 04:54 UTC, merged