[Multiple choice questions] Make "other" text required
google/ground-android pull request #2870
Opened 2024-11-24 06:38 UTC by shobhitagarwal1612

Fixes #2833

Disables the previous/next buttons if the task is required and user has selected other option but hasn't filled the text.

Verified by running the app locally and via unit tests

@gino-m  PTAL?

2024-11-24 08:33 UTC, anandwana001 approved these changes

2024-11-26 18:31 UTC, gino-m requested changes

2024-11-26 18:31 UTC, gino-m commented on ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt
> +                otherText.trim() != ""
You could use `!task.isRequired || otherText.isNotBlank()` here, though I don't quite get why this would mean the item is selected?

2024-11-26 18:31 UTC, gino-m commented on ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/multiplechoice/MultipleChoiceTaskViewModel.kt
> +    if (task.isRequired && selectedIds.contains(OTHER_ID) && otherText.trim().isEmpty()) {
Please extra into helper function. You can also use `isBlank()` here on `otherText`

2024-11-26 19:33 UTC, shobhitagarwal1612 commented
@gino-m PTAL

2024-11-26 20:42 UTC, gino-m approved these changes
Much clearer, thank you! 🙏

2024-11-27 03:47 UTC, merged