Added Navigation Directions Check
google/ground-android pull request #2889
Opened 2024-12-01 10:45 UTC by anandwana001

Fixes #2776 

@shobhitagarwal1612  PTAL?

2024-12-02 04:38 UTC, shobhitagarwal1612 commented
What would be the side-effect of this fix? The navigation won't happen so the screen won't be moved to the next destination? Can you please try and replicate one scenario forcefully to understand what the user will see?

2024-12-02 04:50 UTC, anandwana001 commented
The user will remain on the screen. However, this type of condition comes to the user in a worst case where the naviations instance are having are issue.

2024-12-02 04:59 UTC, shobhitagarwal1612 commented
I'm not sure if we should silently let the app fail. 

@gino-m Thoughts?

2024-12-02 04:59 UTC, shobhitagarwal1612 commented
@anandwana001 Can you look into options on how to resolve this problem?

2024-12-02 12:19 UTC, anandwana001 commented
@gino-m @shobhitagarwal1612 I did take a look at all the logs again: (updated issue https://github.com/google/ground-android/issues/2776) logs

1. submissionConfirmationDialogFragment - no more exists
2. showTermsOfService - the terms_of_service_fragment is trying to open itself again using the navigate() function
3. showOfflineAreas - the offline_areas_fragment is trying to open itself again using the navigate() function

Not reproable, but as per the understanding the `_navigateRequests` flow which is the source emitting the destinations is fixed in this PR, as earlier the scope was different.

2024-12-02 15:55 UTC, gino-m commented
> Not reproable, but as per the understanding the `_navigateRequests` flow which is the source emitting the destinations is fixed in this PR, as earlier the scope was different.

In this PR, the lifecycle is still bound to the Activity, which is the wrong scope, since the fragment requesting the navigation may already be gone by the time the Activity receives the requests. 

Can we instead remove `Navigator` and related code in `MainActivity`, an instead opt for the simpler approach of ViewModel-scoped navigation as described in https://developer.android.com/guide/navigation?

2024-12-03 20:07 UTC, gino-m requested changes

2024-12-04 01:43 UTC, anandwana001 commented on ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt
> +      viewLifecycleOwner.lifecycle.repeatOnLifecycle(Lifecycle.State.RESUMED) {
`viewLifecycleOwner.lifecycleScope.launch {}` 
 Here, the `lifecycleScope` is tied to the view of the fragment
 
 `lifecycleScope.launch {}` 
 Here, the `lifecycleScope` is tied to the fragment itself
 
 https://developer.android.com/guide/fragments/lifecycle

2024-12-04 03:01 UTC, anandwana001 commented on ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt
> +      viewLifecycleOwner.lifecycle.repeatOnLifecycle(Lifecycle.State.RESUMED) {
updated

2024-12-04 17:48 UTC, gino-m approved these changes
In many cases case `UiState` isn't actually modeling states, but actually actions/events. Can we rename those to `NavEvent` in a fast-follow?

Also, in cases `UiState` classes are used in a `SharedStateFlow`, could we please switch those over the a `SharedFlow` if it makes sense?

Filed https://github.com/google/ground-platform/issues/2105 to track.

2024-12-05 03:07 UTC, merged