Added single todo ticket for untracked todos
google/ground-android pull request #2904
Opened 2024-12-09 07:20 UTC by anandwana001

Fixes #2178

Using the ticket #2903 to track all the untracked tickets buy creating sub-tickets in it

@gino-m  PTAL?

2024-12-09 15:05 UTC, gino-m requested changes
Thanks @anandwana001 for adding the detekt check. A single ticket isn't really helpful for tracking those TODO, though - ideally we'd have a ticket for each issue or class of issues.

Also note that I've started adding the full URL of the ticket to the `TODO()` tag so that they're clickable in Android Studio. That will usually cause the TODO to wrap onto the next line, in which case you can intent two spaces to ensure AS interprets the second line as part of the same TODO.

2024-12-10 06:19 UTC, anandwana001 commented
@gino-m 
The goal of this PR:

1. To enable the TODO format check
2. All the untracked TODO, will be connected with a single issue #2903, where any developer in the future can create sub-tickets and work on it.
3. As per the PR, there are 38 untracked issues, for which we have to create individual tickets with all details, might take time, and block us from enabling the TODO format check

Hence this PR. 

Updating the detekt check as per the suggestion for a clickable link

2024-12-10 17:36 UTC, gino-m requested changes
I've added links to appropriate issues, creating them where appropriate. 

Idea: Can we use https://github.com/marketplace/actions/todo-to-issue to auto-generate issues for each TODO as they're added in the future? In that case we'd have a different format for TODO URLs:

```
// TODO: Todo description
// Issue URL: ...github url.
```

@shobhitagarwal1612 @scolsen Wdyt? If you agree I can enable the plugin and try it out.
Wdyt? If you like the idea I can enable the plugin for you to try out.

2024-12-12 14:13 UTC, gino-m commented
We spoke. 
- [ ] @shobhitagarwal1612 will set up the GitHub action to create issues on merge to `master`.
- [ ] @anandwana001 Please move URLs to 2nd line as "Issue URL" (see above)
- [ ] @anandwana001 Also update check to require TODOs to look like `// TODO: ...`

2024-12-16 15:14 UTC, gino-m requested changes
Once nit, otherwise LGTM

2024-12-16 15:14 UTC, gino-m commented on config/detekt/detekt.yml
> +        allowedPatterns: '^//\s*TODO:\s+.+'
There should be exactly one before, and one space after "TODO", so `^//.TODO:/.` Multiple arbitrary whitespace shouldn't be allowed (e.g., "~//&nbsp;&nbsp;&nbsp;&nbsp;TODO:&nbsp;&nbsp;&nbsp;Do something~")

2024-12-16 15:14 UTC, gino-m commented on ground/build.gradle
> +    // Issue URL: https://github.com/google/ground-android/issues/1748
Thanks for making these changes

2024-12-18 15:19 UTC, gino-m approved these changes

2024-12-18 19:09 UTC, gino-m requested changes

2024-12-18 19:09 UTC, gino-m commented on config/detekt/detekt.yml
> +        allowedPatterns: '^//\s*TODO:\s+.+$'
Sorry my original suggestion wasn't correct, but this also seems like the original regex. I think you want this:

`allowedPatterns: '^// TODO: .+$'`

2024-12-19 15:29 UTC, gino-m approved these changes

2024-12-19 16:08 UTC, merged