Introduce TaskSequenceHandler for data collection
google/ground-android pull request #2959
Opened 2024-12-31 11:48 UTC by shobhitagarwal1612

Towards #2958 

Introduce a new interface `TaskSequenceHandler` which exposes all the functionality required for computing the sequence and related helper methods.

This will be later used in `DataCollectionViewModel` to replace all task sequence related code with this handler. 

@anandwana001 @gino-m PTAL?

2025-01-06 19:36 UTC, scolsen requested changes
Nice! A couple of suggestions. Nothing crazy, and you can reject them if needed/

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
> +interface TaskSequenceHandler {
Do we really expect to have to override this? If not, consider making this concrete and removing the need for a separate Impl class. Alternatively, we could make this an `open` class to bundle the interface with the default implementation (if we do expect to need to override these with alternatives).

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +class TaskSequenceHandlerImpl(
If we do keep the interface, the distinguishing feature here, and the required data is the list of tasks, which must be non empty. You can probably better distinguish this class by naming it after that requirement, e.g.:

`NonEmptyTaskListSequenceHandler` or similar.

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +    if (tasks.isEmpty()) {
Nit: Consider using `require`, throwing an `IllegalArgument` exception instead.

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +  private val shouldIncludeTask:
I think it might get a little tricky to use this correctly, and it seems overly general for now. IIUC, the intention here is to use `TaskData` instead of the given `Task` whenever the task in question matches the id.

If that's the case, I would inline the ID check directly instead of letting callers provide their own Boolean function. 

I think we should start with relatively limited functionality here and generalize and expand only if it eventually becomes necessary (unless we already need to do this based on the existing patterns in the codebase, in which case, ignore this).

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +  private val shouldIncludeTask:
Another thing to consider is that this is basically doing two things. 1. Giving users a way to simply filter tasks (don't include x if it matches id y) and 2. giving users a way to replace tasks (replace x with y if id of x == some string). Separating these two functions might make it easier to use this and clearer, even though they are both instances of the same general idea.

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +    return taskId == getTaskSequence(taskValueOverride = taskId to value).last().id
I found this confusing to understand at first. Wouldn't the basic boolean check:

```
val last = getTaskSequence.last()
taskId == last.id && value == last.getValue()
```

be simpler?

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +    return taskId == getTaskSequence(taskValueOverride = taskId to value).last().id
Note also that the current implementation will throw if the sequence happens to be empty after filtering.

If you separate out the call to last instead you can check for this and simply return false.

2025-01-06 19:36 UTC, scolsen commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +    checkInvalidIndex(taskId, index)
Consider returning a sentinel `-1` value instead of throwing. This is in keeping with the semantics of `indexOfFirst` and would allow you to make this just `return getTaskSequence().indexOfFirst { it.id == taskId }`.

I would generally avoid throwing unless we need to really flag checking for a task no in the collection as an exceptional case (which might be the correct thing here, I trust your call on this)

2025-01-07 02:26 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
> +interface TaskSequenceHandler {
That's a great point! We won't have another fake implementation of this interface as the normal one can be directly used in unit tests. Will drop the interface and merge with concrete class

2025-01-07 09:52 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
> +interface TaskSequenceHandler {
Done

2025-01-07 09:53 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +class TaskSequenceHandlerImpl(
Already replaced the interface with concrete class. Resolving this.

2025-01-07 10:03 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +    if (tasks.isEmpty()) {
Done

2025-01-07 11:43 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +  private val shouldIncludeTask:
The `Task` entity includes a `condition` field, which contains a list of `expressions` used to determine whether a multiple-choice task has a specific set of selected values. During sequence computation, we evaluate this condition (if present) to decide if the task should be included or filtered out. To perform this evaluation, access to the `taskDataMap` for all tasks is necessary. Instead of passing the `taskDataMap` to each method, I opted for a callback in the implementation to avoid direct propagation of the map. However, I acknowledge this approach may appear complex and unintuitive. Do you have suggestions for a cleaner way to retrieve task values in this handler or delegate condition evaluation to a dedicated class?

FYI, this is how it was planned to be used in the current structure.
https://github.com/google/ground-android/pull/2986/files#diff-0f12b194c69d844eb8ddb61645fd78f49d11f76701c884cef7464c66fb978764R141-R142

2025-01-07 13:00 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +    checkInvalidIndex(taskId, index)
Up until this point, we were assuming -1 means first task. IMO, that added fragility to the code as instead of failing the application, we were sometimes jumping tasks if something couldn't be found. So, to identify all those default cases, I added the task id empty check and index out of bounds check. 

Let me re-evaluate if we can live without throwing the errors. Thanks again!

2025-01-07 18:01 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +    return taskId == getTaskSequence(taskValueOverride = taskId to value).last().id
Added a TODO to address this issue while integrating with the view model.

2025-01-08 02:43 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandler.kt
> +   * This function determines the order of tasks to be presented, taking into account any overrides
Done

2025-01-08 02:43 UTC, shobhitagarwal1612 commented on ground/src/main/java/com/google/android/ground/ui/datacollection/TaskSequenceHandlerImpl.kt
> +  private val shouldIncludeTask:
Done

2025-01-08 02:47 UTC, shobhitagarwal1612 commented
Thanks @scolsen for the thorough review! I'll try to resolve some of the comments in the subsequent PR where this handler will be used in the VM.

2025-01-08 02:47 UTC, merged