[Code health] Clean up remote persistence observables
google/ground-android pull request #704
Opened 2021-01-18 14:01 UTC by gino-m

Work towards #699.

2021-01-20 13:06 UTC, shobhitagarwal1612 requested changes

2021-01-20 13:06 UTC, shobhitagarwal1612 commented on gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteStorageManager.java
>    /** Fetches url of a remote file path. */
Please remove the old comment.

2021-01-20 13:06 UTC, shobhitagarwal1612 commented on gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeaturesCollectionReference.java
> +  @Cold
`terminates = false`?

2021-01-20 13:18 UTC, gino-m commented on gnd/src/main/java/com/google/android/gnd/persistence/remote/RemoteStorageManager.java
>    /** Fetches url of a remote file path. */
Done! Probably some merging mess.

2021-01-20 13:18 UTC, gino-m commented on gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/FeaturesCollectionReference.java
> +  @Cold
Good catch!

2021-01-20 13:19 UTC, gino-m commented
Thanks @shobhitagarwal1612, PTAL!

2021-01-27 03:04 UTC, gino-m commented
> Thanks @shobhitagarwal1612, PTAL!

@shobhitagarwal1612  Fixes some failing checks, please take a look?

2021-01-27 05:37 UTC, shobhitagarwal1612 approved these changes

2021-01-27 05:37 UTC, merged