[DRAFT] Sync status
google/ground-android pull request #951
Opened 2021-07-09 18:47 UTC by scolsen

2021-07-09 20:34 UTC, scolsen commented
/gcbrun

2021-07-09 20:36 UTC, scolsen commented
@gino-m ready for a review! Thanks for your help!

2021-07-09 22:16 UTC, gino-m commented
@scolsen From the screenshot look like it's still dumping the feature id instead of the caption. Could you PTAL?

2021-07-11 22:28 UTC, gino-m requested changes

2021-07-13 16:33 UTC, scolsen commented on gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusListAdapter.java
> +            .append(feature.getId())
This method doesn't seem to exist.

2021-07-13 16:35 UTC, scolsen commented on gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusListAdapter.java
> +            .append(feature.getId())
@gino-m do you have it defined in some branch other than master?

2021-07-13 16:39 UTC, gino-m commented on gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusListAdapter.java
> +            .append(feature.getId())
Errata corrige: `featureHelper.getCaption(...)`

2021-07-13 16:50 UTC, scolsen commented on gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusListAdapter.java
> +            .append(feature.getId())
Oh got it, thanks!

2021-07-13 16:51 UTC, scolsen commented on gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusListAdapter.java
> +            .append(feature.getId())
Looks like `getCaption` is private and `getLabel` calls `getCaption` anyway.

2021-07-13 22:34 UTC, gino-m commented on gnd/src/main/java/com/google/android/gnd/ui/syncstatus/SyncStatusListAdapter.java
> +            .append(feature.getId())
Please lmk when it's ready for another look!

2021-07-26 19:19 UTC, scolsen commented
/gcbrun

2021-07-26 19:20 UTC, scolsen commented
@gino-m ready for another look

2021-07-26 20:46 UTC, gino-m commented
/gcbrun

2021-07-26 20:46 UTC, gino-m approved these changes

2021-07-26 21:45 UTC, merged