[UX] Show location accuracy on map
google/ground-android pull request #983
Opened 2021-08-07 08:50 UTC by shobhitagarwal1612

Fixes #979

@gino-m  PTAL?

2021-08-09 15:01 UTC, gino-m requested changes
Thanks for implementing this much needed feature. Could you add a screenshot to the PR description so we can tweak the UI before merging?

2021-08-09 15:01 UTC, gino-m commented on gnd/src/main/res/layout/map_container_frag.xml
> +          android:background="@color/colorAccent"
Maybe white background, primary color text?

2021-08-10 03:36 UTC, shobhitagarwal1612 commented on gnd/src/main/res/layout/map_container_frag.xml
> +          android:background="@color/colorAccent"
Done

2021-08-10 03:37 UTC, shobhitagarwal1612 commented
![image](https://user-images.githubusercontent.com/8918023/128804517-85af14a5-0349-4eac-885f-6e087ee6b81a.png)

2021-08-13 16:16 UTC, shobhitagarwal1612 commented
@gino-m Does it look ok?

2021-08-13 16:19 UTC, gino-m approved these changes
Sorry for the delay. LGTM!

I think in the future we may want to ask for UX help (@coreyleamon, @jacobmclaws ) on a more robust way to represent location accuracy, since the text may be long in other languages, and may not be obvious to non-technical folks. That said, for a first pass this works great!

2021-08-13 16:20 UTC, gino-m commented
/gcbrun

2021-08-13 18:44 UTC, merged